// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-A9kSeEa26gnVB7mDXnJ2E27_gV_ViTI',
    appId: '1:770259883594:web:c1569cad97ed290592f8b3',
    messagingSenderId: '770259883594',
    projectId: 'ink-talk-24c71',
    authDomain: 'ink-talk-24c71.firebaseapp.com',
    storageBucket: 'ink-talk-24c71.firebasestorage.app',
    measurementId: 'G-2XRNTHHVXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzdpUajxPiXDxo6qH2Y2JPX2i8KaF0ZTI',
    appId: '1:770259883594:android:60b207d2a2d13d8592f8b3',
    messagingSenderId: '770259883594',
    projectId: 'ink-talk-24c71',
    storageBucket: 'ink-talk-24c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Bsfzvdw1SyoSpPjEiFWcTR59o3Gp88c',
    appId: '1:770259883594:ios:3ae2722088a3a64192f8b3',
    messagingSenderId: '770259883594',
    projectId: 'ink-talk-24c71',
    storageBucket: 'ink-talk-24c71.firebasestorage.app',
    iosBundleId: 'com.example.inkApp',
  );
}
